services:
    start:
        image: ghcr.io/thedevs-cz/php:8.3
        restart: unless-stopped
        tty: true
        volumes:
            - ./start:/app
        ports:
            - "8080:80"
        environment:
            SERVER_NAME: :80
